# Generated by Django 2.1.3 on 2018-12-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gknybk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betetkonyv_user',
            name='betetkonyv',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='sorsolas',
            name='betetkonyv',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Betetkonyv',
        ),
    ]
